<?php

namespace AppBundle\Repository;

/**
 * AcudienteEstudianteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AcudienteEstudianteRepository extends \Doctrine\ORM\EntityRepository
{
}
