<?php

namespace AppBundle\Repository;

/**
 * AcudienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AcudienteRepository extends \Doctrine\ORM\EntityRepository
{
}
