<?php

namespace AppBundle\Repository;

/**
 * EstadosFaltasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstadosFaltasRepository extends \Doctrine\ORM\EntityRepository
{
}
