app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    
logout:
   path: /docentes/logout
   
logout_admin:
   path: /administrador/logout
   
logout_estudiantes:
   path: /estudiantes/logout

logout_acudientes:
   path: /acudientes/logout
#login:
#    pattern:   /administrador/login
#    defaults:  { _controller: AppBundle:Security:login }
#login_check:
#    pattern:   /login_check